### ISSUE TITLE
Songbird issue

### ISSUE THREAD

**Issue by Ropscot** [linuxforphp/flarelinux#6]
I am getting this error.

Launching Songbird Node at 127.0.0.1:9650
Songbird node successfully launched on PID: 121jq: parse error: Invalid numeric literal at line 1, column 10
jq: parse error: Invalid numeric literal at line 1, column 10

Thanks

**Comment by andrewscaya** [comment]
Hello @Ropscot,

Many thanks for reporting the issue!

Since the Songbird Network is still not available to the public, this is quite normal for now. But, if the issue is still present after the launch of the Canary Netowrk on September 27th, we will definitely look into it.

This being said, you can still query your Songbird server for its Blockchain ID, Node ID, etc., using Postman.

We'll leave this issue open until the official launch on the 27th of September.

Thanks again!

**Comment by andrewscaya** [comment]
This issue has also been brought to the attention of Flare Network's core developer team.

https://gitlab.com/flarenetwork/flare/-/issues/63

**Comment by andrewscaya** [comment]
Hello @Ropscot,

We wanted to let you know that the latest version of Flare Linux fixes this issue. If you are not whitelisted, the node will wait (hang) until you get whitelisted by the Flare Team.

Many thanks for reporting the issue!

Best regards,

Andrew
